package com.hybridmesh.relay.messaging.model

enum class GattTransportError {
    NONE,
    PERMISSION_DENIED,
    BLUETOOTH_UNAVAILABLE,
    CONNECTION_FAILED,
    DISCONNECTED,
    SERVICE_DISCOVERY_FAILED,
    CHARACTERISTIC_MISSING,
    NOTIFICATION_SETUP_FAILED,
    MTU_NEGOTIATION_FAILED,
    FRAME_TOO_LARGE,
    WRITE_REJECTED,
    WRITE_FAILED,
    ACK_TIMEOUT,
    ACK_REJECTED,
    PROTOCOL_ERROR,
    IDENTITY_READ_FAILED,
    IDENTITY_DECODE_FAILED,
    INTERNAL_ERROR
}
